"""Tier 0 for PDFs: read the text layer instead of looking at the picture.

A CFDI PDF is almost never a scan. It is generated by the issuer's billing
software or its PAC, printed straight to PDF, and it carries an embedded text
layer — the characters are *in the file*, positioned but not rasterized.

This project spent its whole PDF budget on vision models before checking that.
Measured on four real supplier invoices, against the deterministic parse of
each invoice's own XML:

    field           qwen2.5vl:3b   PaddleOCR-VL   text layer
    uuid                   2/4          4/4          3/4
    total                  1/4          1/4          4/4
    subtotal               1/4          4/4          4/4
    line_amounts             —          4/4          4/4
    latency                68 s         20 s        <0.1 s

The text layer wins on the field that matters most and costs nothing: no
model, no GPU, no tokens, no transcription step that can invent a digit.

It is not a replacement for the vision path, and the numbers say why. One of
the four invoices renders the stamp block — UUID, seals, certificate numbers —
as an image while keeping the labels as text, so the text layer reads
"Folio Fiscal" and finds nothing after it. The two methods fail on different
documents, which makes them complementary rather than ranked: extract what is
there, and send only what is missing to a model.

`has_text_layer` is what separates the two cases. A scan or a photo of an
invoice yields almost no characters, and that is the honest trigger for the
vision path.
"""

from __future__ import annotations

import re

# Below this, the PDF is a scan, a photo, or a wrapper around one image. Real
# CFDI text layers on the sample here run 2800-2950 characters for a
# single-page invoice, so this is an order of magnitude clear of both cases and
# does not need to be precise.
MIN_TEXT_CHARS = 200

# The one field the text layer can recover with no layout reasoning at all.
# A UUID has a shape nothing else on an invoice shares.
UUID_RE = re.compile(
    r"\b[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-"
    r"[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}\b"
)


class TextLayerUnavailable(RuntimeError):
    """The PDF carries no usable text. Rasterize and use the vision path."""


def extract_text_layer(data: bytes) -> str:
    """Every character the PDF declares, in reading order per page."""
    try:
        import pypdfium2
    except ImportError as exc:  # pragma: no cover - depends on the extra
        raise TextLayerUnavailable(
            "pypdfium2 is not installed. Run `pip install -e '.[local]'`."
        ) from exc

    try:
        pdf = pypdfium2.PdfDocument(data)
    except Exception as exc:  # noqa: BLE001 - pdfium raises its own types
        raise TextLayerUnavailable(f"could not open PDF: {exc}") from exc

    try:
        return "\n".join(
            pdf[index].get_textpage().get_text_range() for index in range(len(pdf))
        )
    finally:
        pdf.close()


def has_text_layer(data: bytes, *, minimum: int = MIN_TEXT_CHARS) -> bool:
    """Whether reading beats looking for this document."""
    try:
        return len(extract_text_layer(data).strip()) >= minimum
    except TextLayerUnavailable:
        return False


def find_uuid(text: str) -> str | None:
    """The fiscal UUID, if the text layer contains one.

    Deterministic and worth doing before any model runs: the UUID is the field
    a vision model is most likely to corrupt, because it is a long string of
    characters with no linguistic redundancy to fall back on. When it is in the
    text layer there is no reason to ask a model to read it.

    Returns None rather than guessing when the stamp block was rendered as an
    image, which happens and is exactly the case the vision path exists for.
    """
    match = UUID_RE.search(text)
    return match.group(0).upper() if match else None
