"""Make exported n8n workflows diffable.

This is the piece that decides whether "edit in the canvas, review in git"
actually works or quietly dies after two days.

A raw export carries a pile of state that changes on every save and says
nothing about the flow: server-assigned ids, `updatedAt`, a `versionId`, a
random `webhookId` per webhook node, pixel-exact drag positions. Commit that
and every diff is a wall of noise, so nobody reads them, so the round-trip is
abandoned.

Normalizing means a diff shows exactly what a human changed:

  * volatile server state is dropped
  * node ids are recomputed deterministically from workflow + node name, so a
    node built here and the same node exported from n8n agree
  * positions snap to the layout grid, so nudging a box by three pixels is not
    a change
  * nodes and keys are sorted, so reordering in the UI is not a change either

Sorting nodes by name is safe: n8n determines execution from `connections`,
which are keyed by name, never from array order.
"""

from __future__ import annotations

import json
from typing import Any

from flows.builder.layout import GRID
from flows.builder.nodes import Node

# Server-assigned or per-save state. None of it describes the flow.
VOLATILE_WORKFLOW_KEYS = frozenset(
    {
        "id",
        "versionId",
        "createdAt",
        "updatedAt",
        "active",
        "isArchived",
        "triggerCount",
        "tags",
        "meta",
        "pinData",
        "shared",
        "homeProject",
        "sharedWithProjects",
        "scopes",
        "usedCredentials",
        "staticData",
    }
)

# `webhookId` is regenerated by n8n and is not referenced by anything in the
# file; keeping it would mean a spurious diff every time the flow is re-imported.
VOLATILE_NODE_KEYS = frozenset({"webhookId", "createdAt", "updatedAt"})


def _snap(value: Any) -> Any:
    try:
        return round(float(value) / GRID) * GRID
    except (TypeError, ValueError):
        return value


def normalize(workflow: dict, *, name: str | None = None) -> dict:
    """Return a canonical form of an n8n workflow document."""
    wf_name = name or workflow.get("name") or ""

    nodes: list[dict] = []
    for raw in workflow.get("nodes", []):
        node = {k: v for k, v in raw.items() if k not in VOLATILE_NODE_KEYS}
        node_name = node.get("name", "")
        # Recompute rather than keep: an export carries n8n's random id, a
        # freshly built workflow carries ours. Deriving both from the name is
        # what lets the two compare equal.
        node["id"] = Node(
            name=node_name, type=node.get("type", ""), type_version=node.get("typeVersion", 1)
        ).node_id(wf_name)
        if isinstance(node.get("position"), list):
            node["position"] = [_snap(v) for v in node["position"]]
        nodes.append(node)

    nodes.sort(key=lambda n: n.get("name", ""))

    connections = {
        src: ports for src, ports in sorted(workflow.get("connections", {}).items())
    }

    out = {
        "name": wf_name,
        "nodes": nodes,
        "connections": connections,
        "settings": workflow.get("settings") or {"executionOrder": "v1"},
    }
    for key, value in workflow.items():
        if key not in out and key not in VOLATILE_WORKFLOW_KEYS:
            out[key] = value
    return out


def dumps(workflow: dict) -> str:
    """Serialize canonically: sorted keys, stable indent, trailing newline."""
    return json.dumps(normalize(workflow), indent=2, sort_keys=True, ensure_ascii=False) + "\n"
